library(ape) #this gives the plotting functions for phylogenies
library(phyclust) #this contains ms (Hudsons program)

plot_ms_tree = function(nsamples, ms_options)
  # Plots the phylogenetic tree generated by ms with the given parameters
  # need phyclust and ape libraries
  # library(phyclust);
  # library(ape);
{
  # Run the ms command
  ret.ms <- ms(nsam = nsamples, opts = ms_options);
  # Get the tree in the newick format
  tree.anc <- read.tree(text = ret.ms[3]);
  tree.anc$tip.label = substr(tree.anc$tip.label,2,10)
  l1 = as.numeric(tree.anc$tip.label)
  # Plot the tree
  res1 = plot.phylo(tree.anc,type="phylogram", direction = "downwards", show.tip.label = T,plot=F)
  ylim = res1$y.lim
  ylim[1] = -0.02*ylim[2]
  cvec = c(rep(2,nsamples/2),rep(3,nsamples/2))
  res1 = plot.phylo(tree.anc,type="phylogram", direction = "downwards", show.tip.label = T,y.lim=ylim,tip.color=cvec[l1])
  axis(2)
  
  list(tree=tree.anc, phylo =res1)
}


computeMeanTreeMS <- function(msResults){
  # Computes the mean coalescence tree given a list of trees in the ms class from the ape package
  # 
  # Args:
  #   msResults: the results of the ms command. 
  #
  # Returns:
  #   a phylogeny containing the mean coalescence tree
  totalNbOfTrees <- (length(msResults) - 1)/2
  firstTree <- read.tree(text = msResults[3])
  nbOfTips <- length(firstTree$tip.label)
  coalTimes <- rep(0, nbOfTips-1)
  for(i in seq(1, totalNbOfTrees)){
    currentTree <- read.tree(text = msResults[2*i + 1])
    coalTimes <- coalTimes + coalescent.intervals(currentTree)$interval.length
    #print(coalescent.intervals(currentTree)$interval.length)
  }
  coalTimes <- coalTimes / totalNbOfTrees
  newickTree <- paste("(1:", coalTimes[1], ", 2:", coalTimes[1], ")", sep = "")
  # Building the mean genealogy
  for (i in seq(2, length(coalTimes), 1)){
    newickTree <- paste("(", newickTree, ":", coalTimes[i], 
                        ", ", i + 1, ":", sum(coalTimes[seq(1, i)]), ")", sep = "")
  }
  newickTree <- paste(newickTree, ";", sep = "")
  meanTree <- read.tree(text = newickTree)
  return(meanTree)
}

createNewick <- function(coalTimes){
  # Creates a tree in newick function from coalescence times
  newickTree <- paste("(1:", coalTimes[1], ", 2:", coalTimes[1], ")", sep = "")
  # Building the mean genealogy
  for (i in seq(2, length(coalTimes), 1)){
    newickTree <- paste("(", newickTree, ":", coalTimes[i], 
                        ", ", i + 1, ":", sum(coalTimes[seq(1, i)]), ")", sep = "")
  }
  newickTree <- paste(newickTree, ";", sep = "")
  newickTree <- read.tree(text = newickTree)
  return(newickTree)
}


