library(ape) #this gives the plotting functions for phylogenies
library(phyclust) #this contains ms (Hudsons program)



plot_ms_tree = function(nsamples, ms_options) #this is the definition of an R function
#the arguments are nsamples - the number of samples (i.e. initial number of lineages at time 0)
#                  ms_options - a character string with the ms command
  # Plots the phylogenetic tree generated by ms with the given parameters
{
  # Run the ms command
  ret.ms <- ms(nsam = nsamples, opts = ms_options);
  # Get the tree in the newick format
  tree.anc <- read.tree(text = ret.ms[3]);
  # Plot the tree
  res1 = plot.phylo(tree.anc,type="phylogram", direction = "downwards", show.tip.label = F)
}
#this makes a 2 by 3 set of plots (op stores the old settings)
op = par(mfrow=c(2,3))
for (i in 1:6){
	#plot_ms_tree(100, "-T")#standard coalescent, sample size 100
	#plot_ms_tree(100,"-T -G 1000")#growing population
	#plot_ms_tree(100,"-T -G -2.119 -eG 2.5 0.0") #declining population
}
par(op)


