library(ape) #this gives the plotting functions for phylogenies
library(phyclust) #this contains ms (Hudsons program)

# Plots the phylogenetic tree generated by ms with the given parameters
# need phyclust and ape libraries
# library(phyclust);
# library(ape);
plot_ms_tree = function(sample_vec, mig)
{
  # Run the ms command
  nsamples = as.integer(sum(sample_vec))
  nislands = as.integer(length(sample_vec))
  ms_options = paste("-T -I ", nislands, " ", paste0(sample_vec, collapse = " "), " ", mig, sep="")
  ret.ms <- ms(nsam = nsamples, opts = ms_options);
  # Get the tree in the newick format
  tree.anc <- read.tree(text = ret.ms[3]);
  tree.anc$tip.label = substr(tree.anc$tip.label,2,10)
  l1 = as.numeric(tree.anc$tip.label)
  # Plot the tree
  res1 = plot.phylo(tree.anc,type="phylogram", direction = "downwards", show.tip.label = T,plot=F)
  ylim = res1$y.lim
  ylim[1] = -0.02*ylim[2]
  cvec <- c()
  for (i in 1:length(sample_vec)) {
    cvec <- c(cvec, rep(i+1, sample_vec[i]))
  }
  #cvec = [rep(i+1, sample_vec[i]) for i in range(1, len(sample_vec))]
  #cvec = c(rep(2,nsamples/2), rep(3,nsamples/2))
  res1 = plot.phylo(tree.anc,type="phylogram", direction = "downwards", show.tip.label = T,y.lim=ylim,tip.color=cvec[l1])
  axis(2)
  
  list(tree=tree.anc, phylo =res1)
}


res1 = plot_ms_tree(c(5, 5, 5), 1)
#the ms command here is for 20 individuals 2 demes with 10 samples from each, and symmetrical migration with 4Nm = 10. 
#The colours correspond to the different demes from which the genes were sampled.
#try also 4Nm=0.1
